apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/issuer: letsencrypt-prod
  name: podinfo
  namespace: dev
spec:
  tls: 
  - hosts:
    - training-user-1.training.weave.works
    secretName: ingress-certificate
  rules:
  - host: training-user-1.training.weave.works
    http:
      paths:
      - backend:
          serviceName: podinfo
          servicePort: 9898
          port: http
        path: /podinfo
  tls:
  - hosts:
    - training-user-1.training.weave.works
    secretName: ingress-certificate
status:
  loadBalancer: {}
